### ISSUE TITLE
Dependencies not available for R version 3.6.1

### ISSUE THREAD

**Issue by NicolasSompairac** [favilaco/deconv_benchmark#1]
Dear @favilaco,

During the installation of dependencies, some packages were returned as "not available for R version 3.6.1": edgeR, DESeq2, limma, pcaMethods, BiocParallel, preprocessCore, SingleR, scater, SingleCellExperiment, Linnorm, DeconRNASeq, multtest.

This might come from the fact that you are using the `install.packages()` command, which indeed can go for different package repositories where these packages are not available.

By using the `BiocManager::install()` command, these packages can be installed without probem :)

**Comment by favilaco** [comment]
Hi @NicolasSompairac !

Thank you very much for pointing this out. You are completely right! 
Perhaps those packages were present in the Spanish CRAN repository I chose but not in all... 

I have amended the README and hopefully will help other people as well.

Happy 2020 ;)

Francisco
