### ISSUE TITLE
Raw gene counts vs log2CPM ( edgeR ) 

### ISSUE THREAD

**Issue by RK1912** [favilaco/deconv_benchmark#3]
Hi , 
I am trying to use these methods for another dataset - for which I have the following data :
1. Log2CPM 
2. UMI counts 
Running the pipeline with the CPM data gave me good RMSE (~0.05) and correlation values (~0.8). However, its not the same for  the UMI counts. Here I am only using the methods that use scRNA-seq data as reference, but I noticed that several of these methods perform better with raw counts. But this is not the case here. 
Can you help me understand where the problem might be or do you have any suggestion as to what works best for this pipeline?

Thanks , 
RK

**Comment by favilaco** [comment]
Hi,

Could you provide more information about: i) what kind of sequencing technology was used to generate the data; ii) how you've processed it so far; iii) which mixture(s) you are trying to deconvolve? 

You also mentioned you are focusing on methods using scRNA-seq as reference. Is this reference based on > 1 subject? Otherwise MuSiC and SCDC cannot be used. My guess would be that DWLS should be giving you good results. 

Best,
Francisco

**Comment by RK1912** [comment]
Hi Francisco, 
The scRNA-seq was performed with CEL-seq2 method. The samples are sorted cell populations from synovial fluid of 51 patients, which were initially sorted into 384-well plates. The final paired end cDNA library was sequenced on HiSeq 2500. The reads are mapped to hg19 with STAR 2.5.2b and outliers were removed with Picard. Gene levels were quantified with UMIs. The raw UMI counts are provided in the data source. But the study originally converted the counts to log2CPM. 

Here is the link to the study and the data source: 
https://www.nature.com/articles/s41590-019-0378-1
https://www.immport.org/shared/study/SDY998

Thanks for your help!

**Comment by favilaco** [comment]
Hi,

I am afraid I don't have access to neither of the two links (the article is not Open Access+ the raw data in dbGap needs username and so does the processed version at immport)... so I'm afraid I cannot help further there.

In any case, going back to your original post, CPM represent linear counts that are already normalized based on library size. Therefore, a good performance there is to be expected.

Finally, I don't understand very well what you meant by: "Here I am only using the methods that use scRNA-seq data as reference, **but I noticed that several of these methods perform better with raw counts. But this is not the case here**." Could you clarify how you reached those conclusions?

I will be out of the office for one week, so won't be able to reply (if needed) till I am back.

Kind regards,

Francisco

**Comment by RK1912** [comment]
Hi Francisco, 
Thanks for your reply. What I meant when I said that several of these methods perform better with raw counts is that these methods suggest to use raw counts in their papers. 
I am able to achieve a good performance for MuSiC and BisqueRNA, but the other 3 methods are throwing some errors. 
For example , when I use DWLS , I am always getting the error :
```
Error in solve.QP(D, d, A, bzero) : 
  matrix D in quadratic function is not positive definite! 
```
I tried running this with CPM data as well as raw counts and I still get this error. I am not sure if I am thinking in the right direction. 
Please do let me know if you have faced this issue and if you can shed some light on why I get this error . 

Thanks , 
RK

**Comment by favilaco** [comment]
Hi RK,

For such specific problems (method-dependent) I would recommend you to open an issue on the author's GitHub (e.g. for DWLS: [https://bitbucket.org/yuanlab/dwls/src/master/])

For that error I found two possible fixes (but again, I think it's best the authors fix it themselves in their repo, that way other users won't encounter the problem in the future):
a) https://stackoverflow.com/questions/28381855/r-function-solve-qp-error-constraints-are-inconsistent-no-solution
b) https://stackoverflow.com/questions/39129253/error-in-solve-qp

Hope this helps!

Francisco

**Comment by RK1912** [comment]
HI Francisco, 

Thanks for your help. 
I also have a small suggestion . 
I realized that in the generator() function, you use the full_phenodata to generate the 1000 pseudo bulk mixes because of which the final matrix P has more cell types than the final estimated cell types from pseudo bulk mixes, because we filter some of the cell types before makign the trainign set. So I would suggest using pData in generator() to make the pseudo bulk mixes. 

Do let me know if this makes sense?  

Thanks 
RK

**Comment by favilaco** [comment]
Hi,

The Generator function uses phenoData as the second parameter. If you wish to use a smaller version of phenoData (e.g. excluding a cell type) you can already do so when specifying such parameter to the function. "cell.distribution" will be built using such info. Hence, the body of the function doesn't need to be changed.

Best,
Francisco

**Comment by RK1912** [comment]
Hi 
Thanks . 
Another thing I noticed today was when I tried to use the TPM data transformation. Apparently, the SingleR package doesn't have the TPM() method? I installed it via BiocManager. 

RK

**Comment by favilaco** [comment]
As stated in the README of this repository, to be able to get SingleR::TPM() you should install it using "devtools::install_github("dviraran/SingleR@v1.0")"
