### ISSUE TITLE
how to prepare data from single cell objects for multiple subjects? 

### ISSUE THREAD

**Issue by complexgenome** [favilaco/deconv_benchmark#4]
Dear favilaco,

Thanks for sharing the code for the deconv paper. 
I am interested to perform deconvolution on bulk rna sequencing data (in-house) and single-cell from publicly available repositories.

I have single-cell object per subject. The input needed for most tools is one object with multiple subjects. However, the tutorial, nor paper mentions how to make one object from different single-cell object.

Is there any guidance on how to combine/merge one expression object from multiple subjects? Is it a list?

Sorry, this has nothing to do with your paper, however, there are no methods/tutorials on how they managed to pull this off.

best,
Sanjeev S

**Comment by favilaco** [comment]
Dear sariya,

I guess you can start by creating your own SingleCellExperiment object merging all individuals:
` sce = SingleCellExperiment::SingleCellExperiment(assays = list(counts = merged_matrix, ... ))`

Next, depending on whether the multiple subjects come from the same experiment & batch or not, you will need to just normalize the data (former case) or batch correct + normalize the data.

Hope this helps!

Francisco
