### ISSUE TITLE
CIBERSORT.R is missing

### ISSUE THREAD

**Issue by HediaTnani** [favilaco/deconv_benchmark#5]
Hi,

Is it possible to get the script CIBERSORT.R.

Thanks a lot.

Hédia

**Comment by favilaco** [comment]
Dear Hédia,

I am afraid I cannot provide it myself. As stated in "References to other methods included in
our benchmark":

While our work has a BSD (3-clause) license, you may need to obtain a
license to use the individual normalization/deconvolution methods (e.g.
CIBERSORT. The source code for CIBERSORT needs to be asked to the authors
at https://cibersort.stanford.edu).

You should contact the authors directly.

Best,
Francisco
